name: Test Build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: scrooge-runner-test
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Debug
      run: |
        pwd
        echo ${GOPATH}
        echo ${GOROOT}

# env:
#   HOME: "/home/ghactions/scrooge/work/"
#   GOPATH: "/home/runner/rechargeapp/work/rechargeapp/go"
#   GO111MODULE: on
# #   GOPRIVATE: "github.com/tokopedia/*"
  
# jobs:
#   test:
#     strategy:
#       matrix:
#         go-version: [1.14]
#         os: [scrooge-runner-test]
#     runs-on: ${{ matrix.os }}
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
        
#       - name: Install Go
#         uses: actions/setup-go@v2
#         with:
#           go-version: ${{ matrix.go-version }}
          
#       - name: Build
#         run: go build -v ./...
